# This is a basic workflow that is manually triggered

name: generate lists

on:
  workflow_dispatch:

jobs:
  build:
    name: Build list
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository }}:latest"
      credentials:
        username: disposable
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fix resolv config
        run: |
          service unbound restart
          echo "nameserver 127.0.0.1" >/etc/resolv.conf.deploy
          mv /etc/resolv.conf.deploy /etc/resolv.conf
          ping google.com
#      - name: Run script
#        run: ./.generate
