# This is a basic workflow that is manually triggered

name: generate lists

on:
  workflow_dispatch:

jobs:
  build:
    name: Build list
    runs-on: ubuntu-latest
    options:
    container:
      image: "ghcr.io/${{ github.repository }}:latest"
      options: "--dns 127.0.0.1"
      credentials:
        username: disposable
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restart unbound
        run: "service unbound restart"
      - name: Run script
        run: ./.generate
